---
# tasks file for spid-wordpress

- group: name=wp state=present

- user:
    name: wp
    groups: wp
    password: $6$bKkxtL/Xt5Hlmk$vMaUBzm5viW0RAegAOFAljzNfIM9NDwRQ70H4/AAtFeYPaV7x0ybHdxTMsdb4YIaWYtZyfNe6WnFV2yRN2giV0

- name: make sure the directory exists
  file:
    path: "{{ spid_wordpress_dir }}"
    state: directory
    owner: wp
    group: wp
    mode: 0755

- name: install plugin dependencies
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - git
    - composer
    - make
    - openssl
    - php-curl
    - php-zip
    - php-xml
    - php-mcrypt

- name: get the spid-wordpress repo
  git:
    repo: "https://github.com/simevo/spid-wordpress.git"
    dest: "{{ spid_wordpress_dir }}"

- name: install php dependencies with composer
  become: yes
  become_user: wp
  composer:
    command: install
    working_dir: "{{ spid_wordpress_dir }}"

- name: generate the SP certificate
  command: openssl req -x509 -nodes -sha256 -days 365 -newkey rsa:2048 -subj "/C=IT/ST=Italy/L=Rome/O=wordpress/CN={{ spid_wordpress_hostname }}" -keyout {{ spid_wordpress_dir }}/wp.key -out {{ spid_wordpress_dir }}/wp.crt
  args:
    creates: "{{ spid_wordpress_dir }}/wp.crt"

- name: make sure www-data can read the key
  file:
    path: "{{ spid_wordpress_dir }}/wp.key"
    state: file
    group: www-data

- name: add softlink to plugin
  file:
    src: "{{ spid_wordpress_dir }}"
    dest: /var/lib/wordpress/wp-content/plugins/spid-wordpress
    state: link
