---
# tasks file for nginx with php-fpm and SSL

- name: Add self IP address to the hosts file
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ spid_wordpress_hostname }}"
    state: present

- name: install nginx and snakeoil certificates
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - nginx
    - php-fpm
    - ssl-cert

- name: remove symlink to default nginx configuration
  file:
   path: "/etc/nginx/sites-enabled/default"
   state: absent

- name: install the nginx configuration
  template:
    src=wordpress.conf
    dest=/etc/nginx/sites-enabled/wordpress.conf
    owner=root
    group=root
    mode=0644

- name: restart nginx service
  command: systemctl restart nginx

- name: ensure that nginx is started and enabled
  service: name=nginx
           state=started
           enabled=yes
